name: first-github-action
on:
  push:
    branches:
      # When someone push to `main` branch
      - main
jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Checkout the repo on the Staging Server
        run: ssh staging "git clone https://github.com/umars-cloudworld/node-automated.git || true"
           
      - name: Install
        run: ssh staging 'cd node-automated && git pull && npm install -y'

      - name: Lint
        run: ssh staging 'cd node-automated && npm run lint'

      - name: Build the react app
        run: ssh staging 'cd node-automated && npm run build -y' 

      - name: Start the app
        timeout-minutes: 1 # Times out after 1 minute
        run: ssh staging 'cd node-automated && pm2 serve build 80 --spa'
